# Generated by Django 4.2.30 on 2026-07-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accountpayable_attributes_category_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
