# Generated by Django 4.2.30 on 2026-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accountpayable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Atrasado')], default='pending', max_length=20),
        ),
    ]
